### ISSUE TITLE
com.github.saurfang#sbt-spark-submit;0.0.4: not found

### ISSUE THREAD

**Issue by woj-i** [saurfang/spark-tsne#10]
I try to run MNIST example in Intellij, but I have this error in build phase.
```
Error:Error while importing SBT project:<br/>...<br/><pre>[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
Invalid response.
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.github.saurfang#sbt-spark-submit;0.0.4: not found</pre>[...]
```

**Comment by erwinvaneijk** [comment]
Woj-i, this feels more like a intellij issue, than anything else. What version of intellij are you using? I've noticed some issues with intellij not picking up the dependencies, which is partly due to spark-tsne also building for scala-2.10. I needed to tweak the imported files a bit before everything went smoothly.
